Feature/gwdc 69/wp documentation how does the plugin work
towa-digital/gebrueder-weiss-woocommerce pull request #44
Opened 2023-07-13 14:51 UTC by Martin-Welte

# TL;DR

- added plugin setup
- added how it works
- added setup documentation
- added navbar to docs
- added custom styling
- added use cases to documentation

## Additional information:
- can be reviewed here: https://towa-digital.github.io/gebrueder-weiss-woocommerce/#/ Github pages is currently configured to use this branch to deploy. After PR is merged, the setting has to be set to develop branch again.

2023-07-13 15:04 UTC, philipp-hemmer commented on docs/how-it-works.md
> +	1. The payment processor receives the payment for the order and updates the order state. to the fullfillment state *(this would be the default processing state from woocommerce)*
"...the order state. to the" ... the dot is not necessary

2023-07-13 15:10 UTC, philipp-hemmer requested changes
i would recomment to place to the logo on top of the sidebar on the left side

2023-07-13 15:10 UTC, philipp-hemmer commented on docs/how-it-works.md
> +If the Shop offers manual payment options, like bank transfer or similar, in most cases the **orders will be set to "On Hold" by the payment provider** until the order is paid. In this case a Woocomm
themselves

2023-07-14 12:19 UTC, philipp-hemmer approved these changes

2023-07-17 07:21 UTC, thai-phan-towa approved these changes

2023-07-17 12:30 UTC, merged