Feature/gbw sdk/auth mock
towa-digital/gebrueder-weiss-woocommerce pull request #5
Opened 2021-07-15 08:15 UTC by philipp-hemmer

- added oauth2-mockserver  package & config json for accepted keys
- server started along with unit tests **Runs in background - we need a way to stop/kill it properly **
- added manual startscript

2021-07-15 08:33 UTC, lucapircher requested changes

2021-07-15 08:33 UTC, lucapircher commented on composer.json
> +        "guzzlehttp/guzzle": "*",
I would not use any as a version constraint, since this could lead to unexpected major version updates.

2021-07-15 08:33 UTC, lucapircher commented on includes/GbWeiss.php
> +use Towa\GebruederWeissSDK\{Configuration, Api\ReadApi};
I would not include the use statement here since the classes are not used at the moment.

2021-07-15 08:33 UTC, lucapircher commented on tests/bootstrap.php
> +$mockServer = shell_exec('npx oauth2-mock-server --jwk "mockserver/mocked-keys.json" -p 8887 2>&1 | tee -a /tmp/mylog 2>/dev/null >/dev/null &');
If we use the approach of starting a mock oauth server for the tests, please include a test that verifies that this is actually working.

2021-07-19 07:25 UTC, Martin-Welte approved these changes
looks good now

2021-07-19 17:04 UTC, lucapircher commented
I think this PR can be closed since the relevant changes are included in #6

2021-07-20 14:25 UTC, closed without merging