Feature/gwdc 74 different warehouses documentation
towa-digital/gebrueder-weiss-woocommerce pull request #50
Opened 2023-08-03 15:32 UTC by Martin-Welte

# TL;DR

- adds documentation for GBW shipping method
- adds documentation for Plugin settings Shipping Details
- enables search within docsify

2023-08-03 15:49 UTC, philipp-hemmer requested changes

2023-08-03 15:49 UTC, philipp-hemmer commented on docs/gbw-shipping-method.md
> +How you can generally define shipping zone you can read here: [Setting up Shipping Zones](https://woocommerce.com/document/setting-up-shipping-zones/)
i'd write `How shipping zones are defined is documented here`

2023-08-03 15:49 UTC, philipp-hemmer commented on docs/gbw-shipping-method.md
> +In the overlay you can add a specific Gebrüder Weiss Warehouse ID. This is only relevant if you are a customer who has stock in different warehouses from Gebrüder Weiss. You can configure your shippi
supplying

2023-08-03 15:49 UTC, philipp-hemmer commented on docs/gbw-shipping-method.md
> +Per default the `GBW Shipping Method` does not have additional price defined. If you want to override the default shipping rate calculation from the Plugin you can use the filter `gbw_shipping_rate`
has no additional price defined

2023-08-04 09:52 UTC, mattcrn commented on docs/gbw-shipping-method.md
> +If no Warehouse ID is supplied, the default of your account will be used. Please Contact Gebrüder Weiss Support if you have further Questions about this.
contact lowercase

2023-08-04 09:56 UTC, philipp-hemmer approved these changes

2023-08-04 09:57 UTC, mattcrn approved these changes
1 little typo but approved

2023-08-08 06:17 UTC, merged